name: flutter_login_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter_launcher_icons: ^0.7.3
  


  numberpicker: ^1.1.0
  
  flutter_swiper : ^1.1.6
  animated_splash:  ^1.0.0
  
  
  image_picker: ^0.6.0+9
  #parallax_image: ^0.3.1+1
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.3+4  
  http: ^0.12.0
  flutter_local_notifications: ^0.8.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  random_string: ^1.1.0
  firebase_messaging: ^5.1.5
  photo_view:
  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  table_calendar: ^2.0.1
flutter_icons:
  android: true 
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#0000ffff"
  adaptive_icon_foreground: "assets/logo.png"

dev_dependencies:
  
  
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/login.png
   - assets/logo.png
   - assets/register.png
   - assets/addchild.png
   - assets/profile.png
   - assets/+1.png
   - assets/+3.png
   - assets/ac.png
   - assets/pf.png
   - assets/li.png
   - assets/+.png
   - assets/++.png
   - assets/+++.png
   - assets/gg.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
          style: italic
    - family: LuckiestGuy 
      fonts:
        - asset: fonts/LuckiestGuy-Regular.ttf
          style: italic
    - family: Sacramento 
      fonts:
        - asset: fonts/Sacramento-Regular.ttf
          style: italic 
    - family: Pacifico 
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
          style: italic
    - family: IndieFlower 
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
          style: italic      
                          
     


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
